version: '3.8'

services:
  # تطبيق BoAI الرئيسي
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/models  # تجنب مزامنة مجلد النماذج الكبير
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://boai:boai@db:5432/boai
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - boai-network

  # قاعدة بيانات PostgreSQL
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: boai
      POSTGRES_USER: boai
      POSTGRES_PASSWORD: boai
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - boai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U boai -d boai"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis للتخزين المؤقت والجلسات
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - boai-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Prometheus للمراقبة
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: unless-stopped
    networks:
      - boai-network

  # Grafana للتصوير
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    networks:
      - boai-network
    depends_on:
      - prometheus

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  boai-network:
    driver: bridge
